### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by Dennis-Do** [NikolayRag/Yi4kAPI#4]
Hey,

I like to record a video and immediately play it after stop recording. Unfortunately you don't implement DownloadFile.

Is there any other way to get the file?

Why you decide to spare this command out?

Greetings,

Dennis

**Comment by NikolayRag** [comment]
It was possible to download files directly by browser or curl or so, over ordinary http file request - even with partial download.
I dont remember exactly the link, but it was returned by camera at connect. Adding "/DCIM/filename" will complete path.

I've burn my Yi4k long ago, and the project is out of date since then.
If you will remain issue unsolved, write back and ill try to recall exact download path.

**Comment by Dennis-Do** [comment]
Thank you for the very, very quick reply. I don't expected this by such an old topic.
Unfortunately I didn't have much time to follow that up.

But now I get it. Just type the camera IP in a browser's search bar and navigate down to the DCIM Folder.

Some things are easier than exptected.

Thank you very much.
